# Generated by Django 5.2 on 2025-04-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnm', models.CharField(max_length=100)),
                ('lnm', models.CharField(max_length=100)),
                ('email', models.EmailField(default=True, max_length=100)),
                ('password', models.CharField(default=True, max_length=100)),
            ],
        ),
    ]
